# Generated by Django 4.1.2 on 2022-11-01 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conatct',
            options={'verbose_name_plural': 'Contact Table'},
        ),
    ]
