# Generated by Django 4.1.2 on 2022-11-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0003_category_team_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
