# Generated by Django 4.1.2 on 2022-11-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0004_remove_dish_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='discount_price',
            field=models.FloatField(),
        ),
    ]
