# Generated by Django 4.1.2 on 2022-11-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
