# Generated by Django 4.1.2 on 2022-11-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('Burger', 'Burger'), ('Pizza', 'Pizza'), ('Snacks', 'Snacks'), ('sweet', 'sweet')], max_length=6, null=True),
        ),
    ]
