# Generated by Django 4.1.2 on 2022-11-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFood', '0011_dish_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='details',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
    ]
